version: "3.7"

services:
    app:
        build: ./project
        env_file: .env
        volumes:
            - static_data:/code/app/staticfiles/
        depends_on:
            - db

    db:
        build: ./postgresql
        env_file: .env
        volumes:
            - database_data:/var/lib/postgresql/data/

    nginx:
        depends_on:
            - app

volumes:
    database_data:
    static_data:
